#!/bin/bash
set -e

# ==============================================================================
# Entrypoint script for TS3 Music Bot Docker Container
# Starts D-Bus and PulseAudio virtual sound servers, generates the config file
# from environment variables, and launches the Java application.
# ==============================================================================

# Fix ownership of the home directory (handles Windows volume mount permission issues)
echo "Fixing home directory permissions..."
chown -R ts3bot:ts3bot /home/ts3bot

# Ensure dbus session bus is started as ts3bot and environment variable is exported
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    echo "Starting D-Bus session bus..."
    # Launch dbus-launch as ts3bot and evaluate the output in the current environment
    eval $(su -p -s /bin/bash -c "dbus-launch --sh-syntax" ts3bot)
fi

# Ensure PulseAudio is running as ts3bot and virtual devices are initialized
echo "Starting PulseAudio daemon..."
su -p -s /bin/bash -c "pulseaudio --start --exit-idle-time=-1 --system=false" ts3bot

# Wait for PulseAudio to start up and register
for i in {1..10}; do
    if su -p -s /bin/bash -c "pactl info" ts3bot >/dev/null 2>&1; then
        echo "PulseAudio is ready."
        break
    fi
    echo "Waiting for PulseAudio..."
    sleep 0.5
done

# Set PulseAudio default devices (must be run as the user running pulseaudio)
su -p -s /bin/bash -c "pactl set-default-sink VirtualSink" ts3bot || true
su -p -s /bin/bash -c "pactl set-default-source VirtualSink.monitor" ts3bot || true

# Generate the ts3-musicbot.config file dynamically from env variables
CONFIG_FILE="/home/ts3bot/ts3-musicbot.config"
echo "Generating bot configuration at $CONFIG_FILE..."

cat <<EOF > "$CONFIG_FILE"
# Auto-generated by entrypoint.sh from Docker environment variables
API_KEY=${TS3_API_KEY:-}
SERVER_ADDRESS=${TS3_SERVER_ADDRESS:-}
SERVER_PORT=${TS3_SERVER_PORT:-9987}
SERVER_PASSWORD=${TS3_SERVER_PASSWORD:-}
CHANNEL_NAME=${TS3_CHANNEL_NAME:-}
CHANNEL_PASSWORD=${TS3_CHANNEL_PASSWORD:-}
CHANNEL_FILE_PATH=${TS3_CHANNEL_FILE_PATH:-}
NICKNAME=${TS3_NICKNAME:-MusicBot}
MARKET=${TS3_MARKET:-US}
SPOTIFY_PLAYER=${TS3_SPOTIFY_PLAYER:-ncspot}
SPOTIFY_USERNAME=${TS3_SPOTIFY_USERNAME:-}
SPOTIFY_PASSWORD=${TS3_SPOTIFY_PASSWORD:-}
USE_OFFICIAL_TSCLIENT=${TS3_USE_OFFICIAL_TSCLIENT:-true}
ACCEPT_TS_LICENSE=${TS3_ACCEPT_TS_LICENSE:-true}
SC_VOLUME=${TS3_SC_VOLUME:-50}
YT_VOLUME=${TS3_YT_VOLUME:-50}
BC_VOLUME=${TS3_BC_VOLUME:-50}
YT_API_KEY=${TS3_YT_API_KEY:-}
SP_API_KEY=${TS3_SP_API_KEY:-}
SP_CLIENT_ID=${TS3_SP_CLIENT_ID:-}
SP_CLIENT_SECRET=${TS3_SP_CLIENT_SECRET:-}
EOF

# Ensure permissions and ownership are correct on the generated config file
chmod 600 "$CONFIG_FILE"
chown ts3bot:ts3bot "$CONFIG_FILE"

# Log connection details (without sensitive passwords)
echo "--------------------------------------------------"
echo "Starting TS3 Music Bot..."
echo "Nickname:      ${TS3_NICKNAME:-MusicBot}"
echo "Server:        ${TS3_SERVER_ADDRESS:-}:${TS3_SERVER_PORT:-9987}"
echo "Channel:       ${TS3_CHANNEL_NAME:-[Default Channel]}"
echo "Spotify Player: ${TS3_SPOTIFY_PLAYER:-ncspot}"
echo "--------------------------------------------------"

# Run the bot via the Web UI Python wrapper as the ts3bot user
# Forward all arguments
exec su -p -s /bin/bash -c "exec python3 /app/web_ui.py --config \"$CONFIG_FILE\" \"$@\"" ts3bot
