#!/bin/bash
set -e

# ==============================================================================
# Entrypoint script for TS3 Music Bot Docker Container
# Starts D-Bus and PulseAudio virtual sound servers, generates the config file
# from environment variables, and launches the Java application.
# ==============================================================================

# Fix ownership of the home directory (handles Windows volume mount permission issues)
echo "Fixing home directory permissions..."
chown -R ts3bot:ts3bot /home/ts3bot

# Ensure dbus session bus is started as ts3bot and environment variable is exported
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    echo "Starting D-Bus session bus..."
    # Launch dbus-launch as ts3bot and evaluate the output in the current environment
    eval $(su -p -s /bin/bash -c "dbus-launch --sh-syntax" ts3bot)
fi

# Ensure PulseAudio is running as ts3bot and virtual devices are initialized
echo "Starting PulseAudio daemon..."
su -p -s /bin/bash -c "pulseaudio --start --exit-idle-time=-1 --system=false" ts3bot

# Wait for PulseAudio to start up and register
for i in {1..10}; do
    if su -p -s /bin/bash -c "pactl info" ts3bot >/dev/null 2>&1; then
        echo "PulseAudio is ready."
        break
    fi
    echo "Waiting for PulseAudio..."
    sleep 0.5
done

# Set PulseAudio default devices (must be run as the user running pulseaudio)
su -p -s /bin/bash -c "pactl set-default-sink VirtualSink" ts3bot || true
su -p -s /bin/bash -c "pactl set-default-source VirtualSink.monitor" ts3bot || true

# Generate the ts3-musicbot.config file dynamically from env variables
CONFIG_FILE="/home/ts3bot/ts3-musicbot.config"
COMMAND_CONFIG_FILE="/home/ts3bot/ts3-musicbot.commands"
echo "Generating bot configuration at $CONFIG_FILE..."

cat <<EOF > "$CONFIG_FILE"
# Auto-generated by entrypoint.sh from Docker environment variables
API_KEY=${TS3_API_KEY:-}
SERVER_ADDRESS=${TS3_SERVER_ADDRESS:-}
SERVER_PORT=${TS3_SERVER_PORT:-9987}
SERVER_PASSWORD=${TS3_SERVER_PASSWORD:-}
CHANNEL_NAME=${TS3_CHANNEL_NAME:-}
CHANNEL_PASSWORD=${TS3_CHANNEL_PASSWORD:-}
CHANNEL_FILE_PATH=${TS3_CHANNEL_FILE_PATH:-}
NICKNAME=${TS3_NICKNAME:-MusicBot}
MARKET=${TS3_MARKET:-US}
SPOTIFY_PLAYER=${TS3_SPOTIFY_PLAYER:-disabled}
SPOTIFY_USERNAME=${TS3_SPOTIFY_USERNAME:-}
SPOTIFY_PASSWORD=${TS3_SPOTIFY_PASSWORD:-}
USE_OFFICIAL_TSCLIENT=${TS3_USE_OFFICIAL_TSCLIENT:-true}
ACCEPT_TS_LICENSE=${TS3_ACCEPT_TS_LICENSE:-true}
SC_VOLUME=${TS3_SC_VOLUME:-50}
YT_VOLUME=${TS3_YT_VOLUME:-50}
BC_VOLUME=${TS3_BC_VOLUME:-50}
YT_API_KEY=${TS3_YT_API_KEY:-}
SP_API_KEY=${TS3_SP_API_KEY:-}
SP_CLIENT_ID=${TS3_SP_CLIENT_ID:-}
SP_CLIENT_SECRET=${TS3_SP_CLIENT_SECRET:-}
EOF

<<<<<<< HEAD
echo "Generating command configuration at $COMMAND_CONFIG_FILE..."

cat <<EOF > "$COMMAND_CONFIG_FILE"
# Auto-generated by entrypoint.sh from Docker environment variables
COMMAND_PREFIX=${TS3_COMMAND_PREFIX:-!}
HELP=${TS3_HELP_COMMAND:-help}
PLAY=${TS3_PLAY_COMMAND:-play}
QUEUE_ADD=${TS3_QUEUE_ADD_COMMAND:-queue-add}
QUEUE_PLAYNEXT=${TS3_QUEUE_PLAYNEXT_COMMAND:-queue-playnext}
QUEUE_PLAYNOW=${TS3_QUEUE_PLAYNOW_COMMAND:-queue-playnow}
QUEUE_PLAY=${TS3_QUEUE_PLAY_COMMAND:-queue-play}
QUEUE_LIST=${TS3_QUEUE_LIST_COMMAND:-queue}
QUEUE_CLEAR=${TS3_QUEUE_CLEAR_COMMAND:-clear}
QUEUE_SHUFFLE=${TS3_QUEUE_SHUFFLE_COMMAND:-shuffle}
QUEUE_SKIP=${TS3_QUEUE_SKIP_COMMAND:-skip}
QUEUE_STOP=${TS3_QUEUE_STOP_COMMAND:-stop}
QUEUE_NOWPLAYING=${TS3_QUEUE_NOWPLAYING_COMMAND:-nowplaying}
QUEUE_PAUSE=${TS3_QUEUE_PAUSE_COMMAND:-pause}
QUEUE_RESUME=${TS3_QUEUE_RESUME_COMMAND:-resume}
LYRICS=${TS3_LYRICS_COMMAND:-lyrics}
INFO=${TS3_INFO_COMMAND:-info}
SEARCH=${TS3_SEARCH_COMMAND:-search}
EOF

# Ensure permissions are correct on the generated config file
chmod 600 "$CONFIG_FILE"
chmod 600 "$COMMAND_CONFIG_FILE"
=======
# Ensure permissions and ownership are correct on the generated config file
chmod 600 "$CONFIG_FILE"
chown ts3bot:ts3bot "$CONFIG_FILE"
>>>>>>> 706c7889e06a7bfe6abb82eac726de593b27ca23

# Log connection details (without sensitive passwords)
echo "--------------------------------------------------"
echo "Starting TS3 Music Bot..."
echo "Nickname:      ${TS3_NICKNAME:-MusicBot}"
echo "Server:        ${TS3_SERVER_ADDRESS:-}:${TS3_SERVER_PORT:-9987}"
echo "Channel:       ${TS3_CHANNEL_NAME:-[Default Channel]}"
echo "Spotify Player: ${TS3_SPOTIFY_PLAYER:-disabled}"
echo "Command Prefix: ${TS3_COMMAND_PREFIX:-!}"
echo "--------------------------------------------------"

<<<<<<< HEAD
# Run the bot via the Web UI Python wrapper
# Any CLI args passed to docker run will be forwarded
exec python3 /app/web_ui.py --config "$CONFIG_FILE" --command-config "$COMMAND_CONFIG_FILE" "$@"
=======
# Run the bot via the Web UI Python wrapper as the ts3bot user
# Forward all arguments
exec su -p -s /bin/bash -c "exec python3 /app/web_ui.py --config \"$CONFIG_FILE\" \"$@\"" ts3bot
>>>>>>> 706c7889e06a7bfe6abb82eac726de593b27ca23
