#!/bin/bash
set -e

# ==============================================================================
# Entrypoint script for TS3 Music Bot Docker Container
# Starts D-Bus and PulseAudio with the ts3bot user environment, generates config
# files from environment variables, and launches the Java application wrapper.
# ==============================================================================

TS3_USER="ts3bot"
TS3_HOME="/home/${TS3_USER}"
export HOME="$TS3_HOME"
export USER="$TS3_USER"
export LOGNAME="$TS3_USER"
export XDG_CONFIG_HOME="${TS3_HOME}/.config"
export XDG_CACHE_HOME="${TS3_HOME}/.cache"
export XDG_STATE_HOME="${TS3_HOME}/.local/state"
export XDG_RUNTIME_DIR="/tmp/runtime-${TS3_USER}"

as_ts3bot() {
    runuser -u "$TS3_USER" -- env \
        HOME="$HOME" \
        USER="$USER" \
        LOGNAME="$LOGNAME" \
        XDG_CONFIG_HOME="$XDG_CONFIG_HOME" \
        XDG_CACHE_HOME="$XDG_CACHE_HOME" \
        XDG_STATE_HOME="$XDG_STATE_HOME" \
        XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
        DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-}" \
        DBUS_SESSION_BUS_PID="${DBUS_SESSION_BUS_PID:-}" \
        "$@"
}

echo "Preparing ${TS3_USER} runtime directories..."
mkdir -p \
    "$XDG_CONFIG_HOME/pulse" \
    "$XDG_CACHE_HOME" \
    "$XDG_STATE_HOME" \
    "$XDG_RUNTIME_DIR" \
    "$TS3_HOME/.ts3client"
chmod 700 "$XDG_RUNTIME_DIR"
chown -R "$TS3_USER:$TS3_USER" \
    "$TS3_HOME" \
    "$XDG_RUNTIME_DIR"

if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
    echo "Starting D-Bus session bus..."
    eval "$(as_ts3bot dbus-launch --sh-syntax)"
    export DBUS_SESSION_BUS_ADDRESS
    export DBUS_SESSION_BUS_PID
fi

echo "Starting PulseAudio daemon..."
as_ts3bot pulseaudio --start --exit-idle-time=-1 --system=false

for i in {1..10}; do
    if as_ts3bot pactl info >/dev/null 2>&1; then
        echo "PulseAudio is ready."
        break
    fi
    echo "Waiting for PulseAudio..."
    sleep 0.5
done

as_ts3bot pactl set-default-sink VirtualSink || true
as_ts3bot pactl set-default-source VirtualSink.monitor || true

CONFIG_FILE="${TS3_HOME}/ts3-musicbot.config"
COMMAND_CONFIG_FILE="${TS3_HOME}/ts3-musicbot.commands"
echo "Generating bot configuration at $CONFIG_FILE..."

cat <<EOF > "$CONFIG_FILE"
# Auto-generated by entrypoint.sh from Docker environment variables
API_KEY=${TS3_API_KEY:-}
SERVER_ADDRESS=${TS3_SERVER_ADDRESS:-}
SERVER_PORT=${TS3_SERVER_PORT:-9987}
SERVER_PASSWORD=${TS3_SERVER_PASSWORD:-}
CHANNEL_NAME=${TS3_CHANNEL_NAME:-}
CHANNEL_PASSWORD=${TS3_CHANNEL_PASSWORD:-}
CHANNEL_FILE_PATH=${TS3_CHANNEL_FILE_PATH:-}
NICKNAME=${TS3_NICKNAME:-MusicBot}
MARKET=${TS3_MARKET:-US}
SPOTIFY_PLAYER=${TS3_SPOTIFY_PLAYER:-disabled}
SPOTIFY_USERNAME=${TS3_SPOTIFY_USERNAME:-}
SPOTIFY_PASSWORD=${TS3_SPOTIFY_PASSWORD:-}
USE_OFFICIAL_TSCLIENT=${TS3_USE_OFFICIAL_TSCLIENT:-true}
ACCEPT_TS_LICENSE=${TS3_ACCEPT_TS_LICENSE:-true}
SC_VOLUME=${TS3_SC_VOLUME:-50}
YT_VOLUME=${TS3_YT_VOLUME:-50}
BC_VOLUME=${TS3_BC_VOLUME:-50}
YT_API_KEY=${TS3_YT_API_KEY:-}
SP_API_KEY=${TS3_SP_API_KEY:-}
SP_CLIENT_ID=${TS3_SP_CLIENT_ID:-}
SP_CLIENT_SECRET=${TS3_SP_CLIENT_SECRET:-}
MUSIC_PERMISSION_NICKNAMES=${TS3_MUSIC_PERMISSION_NICKNAMES:-}
MUSIC_PERMISSION_SERVER_GROUPS=${TS3_MUSIC_PERMISSION_SERVER_GROUPS:-}
MUSIC_PERMISSION_CHANNEL_GROUPS=${TS3_MUSIC_PERMISSION_CHANNEL_GROUPS:-}
ADMIN_PERMISSION_NICKNAMES=${TS3_ADMIN_PERMISSION_NICKNAMES:-}
ADMIN_PERMISSION_SERVER_GROUPS=${TS3_ADMIN_PERMISSION_SERVER_GROUPS:-}
ADMIN_PERMISSION_CHANNEL_GROUPS=${TS3_ADMIN_PERMISSION_CHANNEL_GROUPS:-}
OWNER_NICKNAMES=${TS3_OWNER_NICKNAMES:-}
COMMAND_COOLDOWN_SECONDS=${TS3_COMMAND_COOLDOWN_SECONDS:-3}
EOF

echo "Generating command configuration at $COMMAND_CONFIG_FILE..."

cat <<EOF > "$COMMAND_CONFIG_FILE"
# Auto-generated by entrypoint.sh from Docker environment variables
COMMAND_PREFIX=${TS3_COMMAND_PREFIX:-!}
HELP=${TS3_HELP_COMMAND:-help}
PLAY=${TS3_PLAY_COMMAND:-play}
QUEUE_ADD=${TS3_QUEUE_ADD_COMMAND:-queue-add}
QUEUE_PLAYNEXT=${TS3_QUEUE_PLAYNEXT_COMMAND:-queue-playnext}
QUEUE_PLAYNOW=${TS3_QUEUE_PLAYNOW_COMMAND:-queue-playnow}
QUEUE_PLAY=${TS3_QUEUE_PLAY_COMMAND:-queue-play}
QUEUE_LIST=${TS3_QUEUE_LIST_COMMAND:-queue}
QUEUE_DELETE=${TS3_QUEUE_DELETE_COMMAND:-queue-delete}
QUEUE_CLEAR=${TS3_QUEUE_CLEAR_COMMAND:-clear}
QUEUE_SHUFFLE=${TS3_QUEUE_SHUFFLE_COMMAND:-shuffle}
QUEUE_SKIP=${TS3_QUEUE_SKIP_COMMAND:-skip}
QUEUE_MOVE=${TS3_QUEUE_MOVE_COMMAND:-queue-move}
QUEUE_STOP=${TS3_QUEUE_STOP_COMMAND:-stop}
QUEUE_STATUS=${TS3_QUEUE_STATUS_COMMAND:-queue-status}
QUEUE_NOWPLAYING=${TS3_QUEUE_NOWPLAYING_COMMAND:-nowplaying}
QUEUE_PAUSE=${TS3_QUEUE_PAUSE_COMMAND:-pause}
QUEUE_RESUME=${TS3_QUEUE_RESUME_COMMAND:-resume}
QUEUE_REPEAT=${TS3_QUEUE_REPEAT_COMMAND:-queue-repeat}
HEALTH=${TS3_HEALTH_COMMAND:-health}
SEEK=${TS3_SEEK_COMMAND:-seek}
HISTORY=${TS3_HISTORY_COMMAND:-history}
REPLAY=${TS3_REPLAY_COMMAND:-replay}
LOOP=${TS3_LOOP_COMMAND:-loop}
LOOP_QUEUE=${TS3_LOOP_QUEUE_COMMAND:-loopqueue}
LOOP_OFF=${TS3_LOOP_OFF_COMMAND:-loopoff}
LOOP_STATUS=${TS3_LOOP_STATUS_COMMAND:-loopstatus}
VOLUME=${TS3_VOLUME_COMMAND:-volume}
VOLUME_SHORT=${TS3_VOLUME_SHORT_COMMAND:-vol}
VOLUME_UP=${TS3_VOLUME_UP_COMMAND:-volumeup}
VOLUME_UP_SHORT=${TS3_VOLUME_UP_SHORT_COMMAND:-volup}
VOLUME_DOWN=${TS3_VOLUME_DOWN_COMMAND:-volumedown}
VOLUME_DOWN_SHORT=${TS3_VOLUME_DOWN_SHORT_COMMAND:-voldown}
VOLUME_MUTE=${TS3_VOLUME_MUTE_COMMAND:-mute}
INFO=${TS3_INFO_COMMAND:-info}
SEARCH=${TS3_SEARCH_COMMAND:-search}
GOTO=${TS3_GOTO_COMMAND:-goto}
RETURN=${TS3_RETURN_COMMAND:-return}
EOF

chmod 600 "$CONFIG_FILE" "$COMMAND_CONFIG_FILE"
chown "$TS3_USER:$TS3_USER" "$CONFIG_FILE" "$COMMAND_CONFIG_FILE"

echo "--------------------------------------------------"
echo "Starting TS3 Music Bot..."
echo "Nickname:      ${TS3_NICKNAME:-MusicBot}"
echo "Server:        ${TS3_SERVER_ADDRESS:-}:${TS3_SERVER_PORT:-9987}"
echo "Channel:       ${TS3_CHANNEL_NAME:-[Default Channel]}"
echo "Spotify Player: ${TS3_SPOTIFY_PLAYER:-disabled}"
echo "Command Prefix: ${TS3_COMMAND_PREFIX:-!}"
echo "--------------------------------------------------"

exec runuser -u "$TS3_USER" -- env \
    HOME="$HOME" \
    USER="$USER" \
    LOGNAME="$LOGNAME" \
    XDG_CONFIG_HOME="$XDG_CONFIG_HOME" \
    XDG_CACHE_HOME="$XDG_CACHE_HOME" \
    XDG_STATE_HOME="$XDG_STATE_HOME" \
    XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
    DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-}" \
    DBUS_SESSION_BUS_PID="${DBUS_SESSION_BUS_PID:-}" \
    python3 /app/web_ui.py --config "$CONFIG_FILE" --command-config "$COMMAND_CONFIG_FILE" "$@"
