package ts3musicbot.util

class BotSettings(
    var apiKey: String = "",
    var serverAddress: String = "",
    var serverPort: Int = 9987,
    var serverPassword: String = "",
    var channelName: String = "",
    var channelPassword: String = "",
    var channelFilePath: String = "",
    var nickname: String = "MusicBot",
    var market: String = "",
    var spotifyPlayer: String = "spotify",
    var spotifyUsername: String = "",
    var spotifyPassword: String = "",
    var useOfficialTsClient: Boolean = true,
    var acceptTsLicense: Boolean = false,
    var scVolume: Int = 77,
    var ytVolume: Int = 89,
    var bcVolume: Int = 90,
    var ytApiKey: String = "",
    var spApiKey: String = "",
    var spClientId: String = "",
    var spClientSecret: String = "",
    var musicPermissionNicknames: String = "",
    var musicPermissionServerGroups: String = "",
    var musicPermissionChannelGroups: String = "",
    var adminPermissionNicknames: String = "",
    var adminPermissionServerGroups: String = "",
    var adminPermissionChannelGroups: String = "",
    var ownerNicknames: String = "",
    var commandCooldownSeconds: Int = 3,
)
